name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      name: authenticate to Google Cloud
      with:
        workload_identity_provider: 'projects/7604953608/locations/global/workloadIdentityPools/danta-vishram-wif/providers/dv-provider'
        service_account: 'danta-vishram-service-account@danta-vishram.iam.gserviceaccount.com'

    - id: 'secrets'
      uses: 'google-github-actions/get-secretmanager-secrets@v1'
      name: Get secrets from secret manager
      with:
        secrets: |-
          project_id:projects/7604953608/secrets/project-id
          region:projects/7604953608/secrets/region
          repository:projects/7604953608/secrets/repository
          img:projects/7604953608/secrets/image

    - name: Debug outputs
      run: |
        echo "REGION=${{ steps.secrets.outputs.region }}"
        echo "PROJECT_ID=${{ steps.secrets.outputs.project_id }}"
        echo "REPOSITORY=${{ steps.secrets.outputs.repository }}"
        echo "IMAGE=${{ steps.secrets.outputs.img }}"
                

    - name: Build and push the Docker image
      env:
        region: ${{ steps.secrets.outputs.region }}
        project_id: ${{ steps.secrets.outputs.project_id }}
        repository: ${{ steps.secrets.outputs.repository }}
        img: ${{ steps.secrets.outputs.img }}
      run: |
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-west4-docker.pkg.dev
        docker build -t us-west4-docker.pkg.dev/danta-vishram/danta-vishram-repo/dv-image:latest .
        docker push us-west4-docker.pkg.dev/danta-vishram/danta-vishram-repo/dv-image
      
